### ISSUE TITLE
It thinks movies are episodes

### ISSUE THREAD

**Issue by SubJunk** [tregusti/episode-parser#18]
Is it intended that if it receives a common movie string like `The.Movie.2018.1080p.BluRay.x264-Group.mkv` for example, this library thinks it is episode 18 of season 20?

**Comment by tregusti** [comment]
It is not intended, but the name pattern matches that of an episode. Since there is currently no way to specify what name pattern should and should not be used, this is an undesired outcome of using it on a movie.

But as the name of the package says, it's made for parsing names of episodes, not movies.

**Comment by SubJunk** [comment]
That makes sense, thanks for the response and for the library.
Maybe it would be possible to pass a flag to this library to toggle a more strict mode that doesn't match 4 digits. Just an idea.
